includeNamespace:
- shencq
resource:
  requests:
    cpu: 10m
    memory: 56Mi
  limits:
    cpu: 2000m
    memory: 2048Mi
ekletDeployment:
  deployment:
  - shencq/centos
  nodeSelector:
    "ops.lzwk.com/node-type": eklet
  prefix: "eklet-"
