apiVersion: apps/v1
kind: Deployment
metadata:
  name: set-resource
spec:
  template:
    spec:
      containers:
      - name: set-resource
        volumeMounts:
        - name: config
          mountPath: /app/config
          readOnly: true
      volumes:
      - configMap:
          defaultMode: 256
          name: set-resource-config
          optional: false
        name: config
